---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Dashboard"
subtitle: "AlvarezLAN"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
#message:
  #url: https://b4bz.io
  #style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  #title: "Demo !"
  #icon: "fa fa-grin"
  #content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Proxmox Backup Server"
        logo: "assets/icons/proxmox.png"
        subtitle: "192.168.1.192:8007"
        tag: "app"
        url: "https://192.168.1.192:8007"
      - name: "Proxmox Backup Server Remote"
        logo: "assets/icons/proxmox.png"
        subtitle: "100.77.218.69:8007"
        tag: "app"
        url: "https://100.77.218.69:8007"
      - name: "Sonarr"
        logo: "assets/icons/sonarr.png"
        subtitle: "192.168.1.142:8989"
        tag: "app"
        url: "http://sonarr.alvarezlan.com/"
      - name: "Radarr"
        logo: "assets/icons/radarr.png"
        subtitle: "192.168.1.142:7878"
        tag: "app"
        url: "http://radarr.alvarezlan.com/"
      - name: "Bazarr"
        logo: "assets/icons/bazarr.png"
        subtitle: "192.168.1.236:6767"
        tag: "app"
        url: "http://192.168.1.236:6767"
      - name: "PrivateeringServer1"
        logo: "assets/icons/qbittorrent.png"
        subtitle: "192.168.1.4:7070"
        tag: "app"
        url: "http://192.168.1.4:7070/"
      - name: "PrivateeringServer2"
        logo: "assets/icons/qbittorrent.png"
        subtitle: "192.168.1.4:8080"
        tag: "app"
        url: "http://192.168.1.4:8080/"
      - name: "SABnzb"
        logo: "assets/icons/sabnzbd.png"
        subtitle: "192.168.1.4:6060"
        tag: "app"
        url: "http://192.168.1.4:6060/"
      - name: "Portainer Host"
        logo: "assets/icons/portainer.png"
        subtitle: "192.168.1.236:9996"
        tag: "app"
        url: "http://portainer.alvarezlan.com"
      - name: "Home Assistant"
        logo: "assets/icons/home-assistant.png"
        subtitle: "192.168.1.215"
        tag: "app"
        url: "https://ha.alvareznet.cloud"
      - name: "Nginx Proxy Manager"
        logo: "assets/icons/nginxproxymanager.png"
        subtitle: "192.168.1.183:81"
        tag: "app"
        url: "http://nginx.alvarezlan.com"
      - name: "Slskd"
        logo: "assets/icons/windows98.png"
        subtitle: "192.168.1.236:5030"
        tag: "app"
        url: "https://slskd.alvareznet.cloud/"
      - name: "Prowlarr"
        logo: "assets/icons/prowlarr.png"
        subtitle: "192.168.1.58:9696"
        tag: "app"
        url: "http://192.168.1.58:9696"
      - name: "Tautulli"
        logo: "assets/icons/tautulli.png"
        subtitle: "192.168.1.159:8181"
        tag: "app"
        url: "http://tautulli.alvarezlan.com"  




  - name: "Hosts"
    icon:
    items:
      - name: "Anya"
        logo: "assets/icons/proxmox.png"
        subtitle: "192.168.1.21:8006"
        tag: "Host"
        url: "https://192.168.1.21:8006/"
      - name: "Kanna"
        logo: "assets/icons/proxmox.png"
        subtitle: "192.168.1.25:8006"
        tag: "Host"
        url: "https://192.168.1.25:8006/"
      - name: "Voyager"
        logo: "assets/icons/proxmox.png"
        subtitle: "100.89.200.17:8006"
        tag: "Host"
        url: "https://100.89.200.17:8006"
      - name: "TheHub"
        logo: "assets/icons/unraid.png"
        subtitle: "192.168.1.236"
        tag: "host"
        url: "http://unraid.alvarezlan.com/login"
      - name: "GoingMerry"
        logo: "assets/icons/unraid.png"
        subtitle: "192.168.1.4"
        tag: "host"
        url: "http://192.168.1.4"


  - name: "Syncthing Nodes"
    icon:
    items:
     -  name: "Gomu Gomu"
        logo: "assets/icons/syncthing.png"
        subtitle: "192.168.1.10:8384"
        tag: "Syncthing"
        url: "http://gomusync.alvarezlan.com/"
     -  name: "The Hub"
        logo: "assets/icons/syncthing.png"
        subtitle: "192.168.1.236:8384"
        tag: "Syncthing"
        url: "http://hubsync.alvarezlan.com/"
     -  name: "Remote"
        logo: "assets/icons/syncthing.png"
        subtitle: "100.70.157.87:8384"
        tag: "Syncthing"
        url: "http://100.70.157.87:8384"


  -  name: "DNS"
     icon:
     items:
      - name: "pihole1"
        logo: "assets/icons/pihole.png"
        subtitle: "192.168.1.2/admin"
        url: "http://192.168.1.2/admin"
      - name: "pihole2"
        logo: "assets/icons/pihole.png"
        subtitle: "192.168.1.3/admin"
        url: "http://192.168.1.3/admin"
  
      

        